qml/hookandline_hookmatrix/DropsScreen.qml
avoid rounding fractions of sections up so we don't get 1:60 when clicking hookmatrix drop time buttons.  Fix #42 creating different branch.
=> round fractional seconds down with Math.floor

qml/hookandline_hookmatrix/GearPerformanceScreen.qml
new function to manage relations between gear performance:
1. Exclude must be seleted if Undeployed is selected
2. Lost sinker must be selected if Lost Gangion is selected
3. If lost sinker is deselected, Lost Gangion will be deselected
4. Unselection of all other buttons for No Problems and Undeployed now within func
resolves #145
=> HookMatrix: adding function to control how gp buttons relate

py/hookandline_hookmatrix/Drops.py, py/hookandline_hookmatrix/GearPerformance.py, qml/hookandline_hookmatrix/GearPerformanceScreen.qml, qml/hookandline_hookmatrix/HookMatrixStateMachine.qml
1. GearPerformanceScreen now has widget that mirrors the Hooks label from drops
2. Call updateHooksLabel() in GP on screen load or when user sets all hooks to undeployed
3.  For now make sure state machine pops GearPerformance when going to hooks, so the back button still takes you to Drops from Hooks.
#143
=> HookMatrix: adding button to jump to hooks after gear perf

py/observer/ObserverData.py
fixes JIRA ticket [FIELD-2019](https://www.fisheries.noaa.gov/jira/browse/FIELD-2019).  Applies filter to ObserverData.vessels property to only include vessels not Sunk, Inactive, or Retired.
=> Optecs filter inactive vessels

py/observer/ObserverConfig.py, qml/observer/CatchCategoriesScreen.qml
Fix for https://www.fisheries.noaa.gov/jira/browse/FIELD-2023.  Upon updating the ratio value for weight method 15 on the catch category details page, the corresponding extrapolated weight shown in the selected catch categories table view will also update dynamically.
=> Optecs fix wm15 ratiorecalc

py/observer/Hauls.py, py/observer/ObserverCatches.py, py/observer/ObserverConfig.py, py/observer/ObserverState.py, qml/observer/CatchCategoriesDetailsFGScreen.qml, qml/observer/CatchCategoriesDetailsScreen.qml, qml/observer/CatchCategoriesScreen.qml, qml/observer/ObserverSM.qml
Fix for https://www.fisheries.noaa.gov/jira/browse/FIELD-1894.
Changes relate to trawl weight method 5, which is only allowed use with discarded ZMIS CC and a Species Comp = No.  The WM5 catch weight is calculated by taking the OTC minus all retained weights from the haul.  Anytime a retained entry is altered or the OTC is altered, this weight needs to update.  Summary of the changes in the app is below:
1. WM5 button is only visible when ZMIS is selected
2. When WM5 is selected, Species Comp. = Yes button is hidden, and Species Comp. = No is autoselected
3. the text field for Calculated Weight is the only field visible on the right-hand side of the CC Details Screen
4. This field is readonly and autopopulated with the OTC-RET calculated value
5. If the OTC value is changed, any WM5 catch …
=> Optecs wm5 zmis fix3

py/observer/CatchCategory.py, py/observer/ObserverConfig.py
fix for https://www.fisheries.noaa.gov/jira/browse/FIELD-1219.  Filtering out any CC name that contains the substring "- Target" from the CC selection tableview.  @SaOgaz-NOAA fyi, gonna go ahead and merge, just a one-line change for this fix.
=> Optecs filter targetccs

qml/observer/CatchCategoriesScreen.qml, qml/observer/SpeciesScreen.qml
Adds Catch Num and Species Comp Item ID to CatchCategoriesScreen and SpeciesScreen selection tables: https://www.fisheries.noaa.gov/jira/browse/FIELD-2038 @SaOgaz-NOAA fyi
=> fix FIELD-2038: displaying catch_num and species_comp_item_id

py/observer/ObserverConfig.py, qml/observer/CatchCategoriesFGScreen.qml, qml/observer/CatchCategoriesScreen.qml, qml/observer/ObserverTableView.qml, qml/observer/SpeciesFGScreen.qml, qml/observer/SpeciesScreen.qml
Changes allow TableView sorting to me enabled for Selected CC and Species screens:
1. Add sortable property and sorted signal to ObserverTableView
2. Emit signal when headerDelegate is clicked for sortable ObserverTableView
3. Run custom functionality for selected CC and species tv when sorted is emited
4. Consolidate getSelRow and getSelItem into ObserverTableView
https://www.fisheries.noaa.gov/jira/browse/FIELD-2036
https://www.fisheries.noaa.gov/jira/browse/FIELD-1874
=> Optecs sort cc spp tables

py/observer/ObserverConfig.py, py/observer/ObserverDBSyncController.py, qml/observer/ObserverDBSyncDialog.qml, qml/observer/ObserverHome.qml
Clicking "OK, lets back it up" directs user to backups screen after syncing trip. See https://www.fisheries.noaa.gov/jira/browse/FIELD-2066
=> Suggest backup after successful trip sync

py/observer/Hauls.py, py/observer/ObserverCatches.py, py/observer/ObserverConfig.py, py/observer/ObserverSoundPlayer.py, py/observer/ObserverSpecies.py, qml/observer/BiospecimensScreen.qml, qml/observer/ObserverMatrix.qml, qml/observer/ObserverWeightMatrix.qml, qrc/observer.qrc
See https://www.fisheries.noaa.gov/jira/browse/FIELD-1697
Whats changed:
1. ObserverMatrix.qml created, scrollView with grid of buttons
2. Create button to launch matrix window in BiospecimensScreen; btn mvisible if length-only protocol, or phlb and BSM 10 (and modify button not selected)
3. Allow matrix window to insert length-only biospecimens to tableview, unselecting all when window closed
4. Show basic warnings if small or large lengths are selected
Also created isShrimpGear property in hauls, and replaced some logic to use this feature.  species.isLengthOnlyProtocols is also new and used for matrix enabling.
=> FIELD-1697: Length-only Biospecimen Matrix

doc/dev_env/requirements.pip.txt, doc/dev_env/requirements.virtualenv.python36.txt
dependabot is picking up issues with libraries in the doc/ directory.  Updating requests isn't an issue, software is already using package version 2.20.0.  PyInstaller is still implemented in the GitLab repo, and using 3.6 shouldn't be an issue.  The field-software is also not created using the onefile arg.
=> Resolving old library dependabot issues

qml/observer/ObserverHome.qml
See https://www.fisheries.noaa.gov/jira/browse/FIELD-2107
Change will prevent user from advancing to hauls/sets page unless fishery has been selected.
=> FIELD-2107: force fishery selection before navigation to hauls or sets pages

py/observer/CountsWeights.py, py/observer/ObserverCatches.py, py/observer/ObserverSpecies.py, py/observer/Sets.py, qml/observer/ObserverSM.qml, qml/observer/SetsScreen.qml, qml/observer/SpeciesFGScreen.qml
User can now simply tally dropoff/predated fish and rely on the retained weights from the same species (or complex in certain situations) to auto-calculate the weight. Calculation is kicked off after exiting a set, or via a button on the Species screen. Warnings will pop if retained weights are not available for a given species.
https://www.fisheries.noaa.gov/jira/browse/FIELD-1900
=> New feature to perform auto-calc of Dropoff/Predated fish weights

py/observer/ObserverConfig.py, qml/observer/CatchCategoriesDetailsFGScreen.qml, qml/observer/CountsWeightsFGScreen.qml
Bug causing biospecimen warning prompt when DR15 is selected should be resolved by doing string comparison on discard reason value.  Build 2.1.3+15.
=> FIELD-1910: Cast DR 15 comparison as string

py/observer/CountsWeights.py, py/observer/ObserverConfig.py, py/observer/ObserverDBUtil.py, py/observer/ObserverSpecies.py, py/observer/Sets.py, qml/observer/CountsWeightsFGScreen.qml, qml/observer/SpeciesFGScreen.qml
Several things included on this commit:
- New func in ObserverDBUtil to do decimal rounding
- Avg retained val in calc is correctly rounded
- User can't start tallying without selecting DR reason
- Skate Unid added to skate complex
- Avg val for DR12/15 derived from existing Count/Weight on species screen
- Beefing up comments
tagged with 2.1.3+16
=> FIELD-1900: round calc vals, sticky avg, add skate unid, prevent tally first

py/observer/CountsWeights.py, py/observer/ObserverConfig.py, py/observer/ObserverDBSyncController.py, py/observer/ObserverDBUtil.py, qml/observer/CountsWeightsFGScreen.qml
Creating baskets with default date string format so time is displayed.  Then reformatting for oracle prior to sync.  Better fix is to make sync_upload schema consistent in SPECIES_COMPOSITION_BASKETS and CATCH_ADDITIONAL_BASKETS tables.
=> FIELD-2087: add time to basket created date string first, then recast

py/observer/CountsWeights.py, py/observer/ObserverConfig.py
Existing bug only restricted to hauls and baskets created on the same day, not the current days baskets.  New query gets all baskets created that day.
*Also cleaning up notes field in species comp by rounding avg val.
=> FIELD-1471: Restricting subsample avg calcs to the current day

py/observer/ObserverConfig.py, py/observer/ObserverDBUtil.py
So we now know what Optecs version was being used after trip data is submitted.
Tested sync without any issues.
See https://www.fisheries.noaa.gov/jira/browse/FIELD-2114
=> FIELD-2114: Adding optecs version to data_source

build/build_config.py, build/build_hookandline_hookmatrix.py, py/hookandline_hookmatrix/HookMatrixConfig.py, py/hookandline_hookmatrix/StateMachine.py
Initial commit for hookmatrix versioning.  Follows semvar convention, but uses calendar year in place of generic major version number.
Fix #236
=> Implement hookmatrix versioning

py/hookandline_hookmatrix/HookMatrixConfig.py, py/hookandline_hookmatrix/Hooks.py, qml/hookandline_hookmatrix/HookItem.qml
Highlight fish hooked as green and bold.  Non-fish items (e.g. Bait Back) are pulled from db and will stay as black regular text.  Centering/underlining text labels
Close #82
=> #82: highlight fish caught as green and bold

py/hookandline_hookmatrix/GearPerformance.py, qml/hookandline_hookmatrix/GearPerformanceScreen.qml
Fix #239 Excluded is always selected with Undeployed.  Undeployed is always unselected if Excluded is unselected.
All Gear Performance buttons now use onCheckedChange signal to addGearPerformance/deleteGearPerformance.  Allows code to mark button as checked/unchecked, and implicitly delete DB records.  Removed delete statements from addGearPerformance as they're unnecessary now.
=> #239: Revamp GP button relations.  Auto-select Undeployed/Excluded

py/hookandline_hookmatrix/Drops.py, py/hookandline_hookmatrix/GearPerformance.py, py/hookandline_hookmatrix/StateMachine.py, qml/hookandline_hookmatrix/DropAngler.qml, qml/hookandline_hookmatrix/DropTab.qml, qml/hookandline_hookmatrix/HookMatrixStateMachine.qml
Steps:
1. Create functions in Drops.py to return Drop and Angler IDs and make them available in DropTabl.qml and DropAngler.qml, respectively
2. Create function in Drops.py that uses Angler Op Id to return gear perf label from DB
3. Set gear perf label text with new function in step 2
4. Whenever gear perf is added or removed, signal to UI that label should be updated (only update label for relevant angler id)
Code for previous label updating has been removed.
=> #241: Revised signaling so gear perf labels can persist

py/hookandline_hookmatrix/Drops.py, py/hookandline_hookmatrix/Hooks.py, qml/hookandline_hookmatrix/DropAngler.qml
Steps here:
1. Function in Drops to query hooks by angler op id
2. Format query result with rich QML text, color fish green
3. Set text of hooks label to this label result, if angler op id is available
4. Signal anytime hook is added or deleted to update hook label
Tweak default value for gear perf as well.
=> #79: Format Hooks label on Drops screen

py/hookandline_hookmatrix/GearPerformance.py, qml/hookandline_hookmatrix/DropAngler.qml, qml/hookandline_hookmatrix/GearPerformanceScreen.qml
Steps:
1. Function that updates/inserts hooks 1-5 for current angler created
2. Dialog pops on GearPerformance.qml asking.  Yes calls upsert function
3. After upsert, signal sent to DropAngler to update Hooks label on drops screen.
=> #144: Upsert undeployed hooks from GP screen when Undeployed selected

py/hookandline_hookmatrix/Drops.py, py/hookandline_hookmatrix/GearPerformance.py, py/hookandline_hookmatrix/Hooks.py, qml/hookandline_hookmatrix/DropsScreen.qml, qml/hookandline_hookmatrix/GearPerformanceScreen.qml, qml/hookandline_hookmatrix/Header.qml, qml/hookandline_hookmatrix/HookMatrixStateMachine.qml, qml/hookandline_hookmatrix/HooksScreen.qml
Steps:
1. In HmStateMachine, allow transitions between gp and hooks.  Pop screen off stack if coming from hooks or gp to the other so we can go back to drops directly
2. Revise header to allow forward nav on these screens, and make forward and back text more explicit
3. Use same signalling logic in drops screen to update/format GP and Hooks labels
4. Hide nav to hooks if angler isn't done fishing; function added to drops to check if angler is done.
=> #143: Allow nav between hooks and gp and back

py/observer/CountsWeights.py, py/observer/Hauls.py, py/observer/ObserverConfig.py, py/observer/ObserverDBUtil.py, py/observer/ObserverState.py, py/observer/Sets.py
Bug where query to get current haul created date was using haul num , not haul id.  Issues in debriefer mode where SETTINGS param trip_number was not set due to user mismatch also resolved in ObserverState.
Steps:
1. Also set SETTINGS param trip_number when trip is selected in TripSelectScreen (ObserverState.currentTripId.setter)
2. Set SETTINGS param current_haulset_id to fishing_activity_id in both Hauls and Sets (not haul num)
3. Query subsample calcs using created date of haul using db id and current trip num
4. Move get_current_haulset_createddate() to DBUtil as static method
Also beefing up comments related to FIELD-1471
=> FIELD-1471: Use actual haul DB id to get haul created date, not haul num

py/hookandline_hookmatrix/Drops.py, py/hookandline_hookmatrix/GearPerformance.py, py/hookandline_hookmatrix/HookMatrixConfig.py, py/hookandline_hookmatrix/Hooks.py, qml/hookandline_hookmatrix/DropAngler.qml, qml/hookandline_hookmatrix/DropTab.qml, qml/hookandline_hookmatrix/DropsScreen.qml, qml/hookandline_hookmatrix/GearPerformanceScreen.qml, qml/hookandline_hookmatrix/HooksScreen.qml
Changes do the following:
- #251: Assign angler operation id to DropAngler object when they come available, and keep them static
- #247: Use static angler operation id to decide whether Gear Perf nav is allowed from Drops screen
- #144: Allow autopopulate of angler times to undeployed when selecting GP Undeployed
- #144: ask user if GP is undeployed and hook is changed to something else.
=> #144: HookMatrix Undeployed Autopopulation

py/observer/ObserverConfig.py, py/observer/ObserverDBMigrations.py, py/observer/ObserverDBModels.py, py/observer/ObserverErrorReports.py
See: https://www.fisheries.noaa.gov/jira/browse/FIELD-2100
See: https://www.fisheries.noaa.gov/jira/browse/FIELD-2101
Code changes will allow flag changes in Oracle to sync into Optecs tables.
STATUS_OPTECS flag will disable TERs from running in Optecs at all.  Previously a hard-coded list was used to manually disable TERs that didn't work for various reasons.  We'll now be able to disable from Optecs, OBSPROD, or both.
DEBRIEFER_ONLY flag will allow us to hide TERs from regular users that are only meant for debriefers.
Database files from previous versions should be backwards compatible, adding in fields to TRIP_CHECKS table if missing.
=> FIELD-2100 and 2101:

py/observer/CountsWeights.py, py/observer/ObserverConfig.py, py/observer/ObserverState.py, py/observer/ObserverTrip.py, qml/observer/CountsWeightsScreen.qml, qml/observer/EndTripScreen.qml, qml/observer/ObserverFooterRow.qml, qml/observer/ObserverSunlightButton.qml, qml/observer/TripDetailsFGScreen.qml, qml/observer/TripDetailsScreen.qml
Users will now be required to enter how they're collecting data (direct, direct/form hybrid, forms transcription only) on the Trip Details page.  They'll also be required to enter which forms will be uploaded/submitted on the End Trip page.  These values will be written to the notes field.
The daily avg trawl count feature will be disabled if "Forms Only" collection method is selected.
See: https://www.fisheries.noaa.gov/jira/browse/FIELD-2123
=> FIELD-2123: Add commented fields on data collection method and submitted forms

py/survey_backdeck/FishSampling.py, qml/survey_backdeck/FishSamplingEntryDialog.qml, qml/survey_backdeck/FishSamplingScreen.qml, qml/survey_backdeck/LengthWeightDialog.qml, qrc/survey_backdeck.qrc
Length/Weight relationship check now implemented per issue #94.  Steps Cutter Station goes through:
1. Set current_specimen property value in FishSampling.py using specimenID var from FishSamplingEntryDialog.qml
2. Pull length, weight, and sex from this current specimen
3. Pull LW coefficient (a) and exponent (b) from LENGTH_WEIGHT_RELATIONSHIP_LU table in hookandline_fpc.db
4. Pull tolerance value from SETTINGS table
5. Are either length or weight not filled, but sex is? warn user
6. Do we have all the LW params filled? Predict weight with W = aL^b and apply tolerance range.  Does weight fall within bounds? If not, warn user.
=> CutterStation Length/Weight relationship check branch merged to dev

main_survey_backdeck.py, py/survey_backdeck/Settings.py, py/survey_backdeck/StateMachine.py, qml/survey_backdeck/BackdeckStateMachine.qml, qml/survey_backdeck/SettingsScreen.qml, qml/survey_backdeck/SitesScreen.qml, qrc/survey_backdeck.qrc
Adding ability to update IP address in UI in Cutter Station
1. Connect settings class to SETTINGS table via FramListModel
2. Load up settings model in UI on new settings page as editable tableview
3. Adjust StateMachine for nav purposes
4. When user makes edit, ask to confirm if value has changed
5. Also allow user to select hardcoded defaults for 2021 vessels
6. If IP Address value changes, reboot app
=> #259: Cutter Station settings page initial commit

py/observer/ObserverConfig.py, py/observer/Sets.py, qml/observer/ObserverHome.qml
Do not round average before performing DR/Predated calculation.  Also fixing ability to bypass "Catch Collection Method" entry on Trip Details page by going back out to home screen.
=> FIELD-1900: Rounding error fix, FIELD-2125 nav fix

qml/hookandline_hookmatrix/Footer.qml, qml/hookandline_hookmatrix/HooksScreen.qml, qml/hookandline_hookmatrix/SitesScreen.qml
Print tag buttons for hooks should now be easier to click since they're off the footer and on the right-hand margin of the screen.  Also included is fix for #267 to avoid duplicate print confirmation popup.
Fix #267 
Fix #266
=> #266: Moving HooksScreen print buttons out of footer
