nwfsc-fram/pyFieldSoftware

py/observer/Biospecimens.py
qml/observer/BioViabilityScreen.qml
qml/observer/CatchCategoriesDetailsFGScreen.qml

Optecs fg updates

---

qml/observer/BioSLWScreen.qml
qml/observer/CountsWeightsFGScreen.qml

FIELD-1975 Add Juvenile / Transitional to CA Sheepshead sexes

---

py/trawl_analyzer/TimeSeries.py
qml/trawl_analyzer/main_trawl_analyzer.qml
virtualenv/trawl_analyzer/requirements.txt

https://github.com/nwfsc-fram/boatnet/issues/1120

Fix ValueError, Haul ID Width

---

py/observer/CountsWeights.py

Closes https://github.com/nwfsc-fram/boatnet/issues/1112

Use Decimal for calculations at tally level.

---

py/observer/ObserverCatches.py
py/observer/ObserverConfig.py
qml/observer/TripDetailsFGScreen.qml

* FIELD-1979: Calculate Fixed Gear OTC Weight Method 8 using unrounded total hooks and unrounded sampled hooks

FIELD-1979

---

py/observer/ObserverCatches.py
py/observer/ObserverDBMigrations.py
py/observer/ObserverDBModels.py
py/observer/ObserverDBSyncController.py
py/observer/ObserverSOAP.py
py/observer/Sets.py
py/observer/SyncDBWorker.py
qml/observer/CatchCategoriesDetailsFGScreen.qml
qml/observer/HookCountsDialog.qml
qml/observer/ObserverDBSyncDialog.qml
qml/observer/SetDetailsScreen.qml

Covers https://github.com/nwfsc-fram/boatnet/issues/1184

Optecs updates

---

build/build-observer-all.sh
py/observer/ObserverCatches.py
py/observer/ObserverConfig.py
qml/observer/CatchCategoriesDetailsFGScreen.qml
qml/observer/CatchCategoriesDetailsScreen.qml

Fix OTC Calculation for WM14 on entry/change from CC Details

Fix FIELD-1995

---

qml/observer/CatchCategoriesBasketsScreen.qml

FIELD-1846, FIELD-1847, FIELD-1996 (WM3 zero basket issues, UI issues)

WM3 UI + zero basket fixes

---

py/hookandline_hookmatrix/Hooks.py
py/hookandline_hookmatrix/StateMachine.py
qml/hookandline_hookmatrix/DropAngler.qml
qml/hookandline_hookmatrix/DropsScreen.qml
qml/hookandline_hookmatrix/HookItem.qml
qml/hookandline_hookmatrix/HookMatrixStateMachine.qml
qml/hookandline_hookmatrix/HooksScreen.qml

pulling in changes for easyish features.

Easy issues

---

py/hookandline_hookmatrix/Drops.py
py/hookandline_hookmatrix/StateMachine.py
qml/hookandline_hookmatrix/DropAngler.qml
qml/hookandline_hookmatrix/DropsScreen.qml
qml/hookandline_hookmatrix/GearPerformanceScreen.qml
qml/hookandline_hookmatrix/HookMatrixStateMachine.qml

making hook and gp labels on drops screen in hook matrix populate whenever entering drops screen, and making hooks label conditional on what hooks are populated.

Fix hm drop labels

---

py/hookandline_hookmatrix/GearPerformance.py
qml/hookandline_hookmatrix/GearPerformanceScreen.qml
qml/hookandline_hookmatrix/OkayCancelDialog.qml

Adding method to upsert hook records in catch table.  If exists, update, if not, insert (actual upsert sql didnt work with peewee).  Adjusted OkayCancelDialog, and added in dialog btn to GP.  Also linked exclude and undeployed gp btns.

method to GearPerformance, add dialog and adjust gp behavior

---

py/hookandline_hookmatrix/Drops.py
py/hookandline_hookmatrix/GearPerformance.py
qml/hookandline_hookmatrix/DropsScreen.qml
qml/hookandline_hookmatrix/GearPerformanceScreen.qml
qml/hookandline_hookmatrix/HookMatrixStateMachine.qml

Last few updates to Hook Matrix before doing a build.

Hm gp to hooks btn

---

py/hookandline_hookmatrix/Drops.py
qml/hookandline_hookmatrix/DropAngler.qml
qml/hookandline_hookmatrix/DropsScreen.qml
qml/hookandline_hookmatrix/HookMatrixStateMachine.qml

merging extra branch to address similar functionality for hookmatrix drop screen hook labels

HookMatrix: update hooks label on drops screen

---

build/build_trawl_analyzer.py
py/hookandline_hookmatrix/Drops.py
py/hookandline_hookmatrix/StateMachine.py
qml/hookandline_hookmatrix/DropAngler.qml
qml/hookandline_hookmatrix/DropsScreen.qml
qml/hookandline_hookmatrix/HookMatrixStateMachine.qml

Addresses issue #79 for both gp and hooks labels on the HookMatrix drops screen.  They should now update correctly.

Hookmatrix fix gp labels (and hooks label)

---

py/hookandline_hookmatrix/GearPerformance.py
qml/hookandline_hookmatrix/GearPerformanceScreen.qml
qml/hookandline_hookmatrix/HookMatrixStateMachine.qml
qml/hookandline_hookmatrix/OkayCancelDialog.qml

creates new feature related to #144.

HookMatrix: Popup to set all hooks to undeployed from GP screen

---

qml/hookandline_hookmatrix/HookItem.qml
qml/hookandline_hookmatrix/HooksScreen.qml

highlight hooked fish green, center text on hooks screen
issue #82

Hookmatrix highlight hooked fish

---

qml/observer/CatchCategoriesDetailsScreen.qml
qml/observer/ObserverSM.qml

Fixes JIRA ticket [FIELD-2046](https://www.fisheries.noaa.gov/jira/browse/FIELD-2046).  Commenting out code no longer needed with removal of WM3.  Will remove later after testing, tagged commented code with "TODO: cleanup for WM3 removal"

commenting out code related to WM3 on CatchCatDetails

---

py/observer/ObserverConfig.py
py/observer/ObserverFishingLocations.py
qml/observer/CatchCategoriesDetailsFGScreen.qml
qml/observer/CatchCategoriesDetailsScreen.qml

Older commit of the two is still being fully "approved" but Eric's initial test seems to be that it's working.

Optecs fixes

---

qml/observer/CatchCategoriesDetailsScreen.qml
qml/observer/ObserverSM.qml

may be more to remove, but will address later.  Commented code has been tested, so starting there.

removing commented code for deprecated WM3

---

py/observer/ObserverConfig.py
qml/observer/SpeciesFGScreen.qml
qml/observer/SpeciesScreen.qml

https://www.fisheries.noaa.gov/jira/browse/FIELD-2030, @SaOgaz-NOAA fyi.

fix FIELD-2030, reorder species screen columns FG, Trawl

---

qml/observer/SpeciesFGScreen.qml

Forgot to do changes for fixed gear QML, see https://www.fisheries.noaa.gov/jira/browse/FIELD-2038

Add species_comp_item_id to fixed gear species table

---

qml/observer/CatchCategoriesFGScreen.qml

Adding in fixed gear fix for https://www.fisheries.noaa.gov/jira/browse/FIELD-2038

FIELD-2038 FG fix for CC screen

---

py/observer/ObserverConfig.py
py/observer/ObserverSpecies.py
py/observer/ObserverSpeciesCompModel.py
qml/observer/CatchCategoriesDetailsFGScreen.qml
qml/observer/CatchCategoriesDetailsScreen.qml
qml/observer/CatchCategoriesScreen.qml
qml/observer/CountsWeightsScreen.qml
qml/observer/ObserverTableView.qml
qml/observer/SpeciesScreen.qml

Display count on Species Screen: https://www.fisheries.noaa.gov/jira/browse/FIELD-2040
Hide DR for MIX in Counts/Weights: https://www.fisheries.noaa.gov/jira/browse/FIELD-2028
Bios Prompt from Trawl CC details: https://www.fisheries.noaa.gov/jira/browse/FIELD-2060
Bug fix WMs for PHLB: https://www.fisheries.noaa.gov/jira/browse/FIELD-2073

Optecs 2021 Sprint 2 fixes

---

py/observer/ObserverCatches.py
py/observer/ObserverSpecies.py
qml/observer/CatchCategoriesScreen.qml
qml/observer/CountsWeightsFGScreen.qml
qml/observer/CountsWeightsScreen.qml
qml/observer/ObserverHeader.qml
qml/observer/ObserverSM.qml
qml/observer/ObserverTabsScreen.qml
qml/observer/ProtocolWarningDialog.qml
qml/observer/SpeciesScreen.qml

Feature Adds / Fixes listed below:
- Warning for Counts/Weights No Counts (Trawl Only): https://www.fisheries.noaa.gov/jira/browse/FIELD-2039
- Counts/Weights > 250 Warning (FG & Trawl): https://www.fisheries.noaa.gov/jira/browse/FIELD-1224
- Auto Add Mix Species with WM21 (Trawl Only): https://www.fisheries.noaa.gov/jira/browse/FIELD-2015

Optecs 2020: More sprint 2 fixes

---

py/observer/ObserverConfig.py
py/observer/ObserverSoundPlayer.py
qml/observer/BioSLWScreen.qml
qml/observer/BiospecimensScreen.qml
qml/observer/CountsWeightsFGScreen.qml
qml/observer/GPSEntryDialog.qml
qml/observer/ObserverWeightMatrix.qml
qml/observer/codebehind/CountsWeightsNewBasketSM.js
qrc/observer.qrc

Issues addressed in this merge, see individual commits for more details:
Weight Matrix Entry: https://www.fisheries.noaa.gov/jira/browse/FIELD-1698
Depth = 0 Crash: https://www.fisheries.noaa.gov/jira/browse/FIELD-2079
Biospecimen length < 10 Warning: https://www.fisheries.noaa.gov/jira/browse/FIELD-1851

FG Weight Matrix Entry, BS length < 10, Bad Depth Val Warning

---

py/observer/Hauls.py
py/observer/ObserverConfig.py
py/observer/ObserverState.py
py/observer/Sets.py

See commit messages for more info.

FIELD-2071: Fix trip and haul comment parsing

---

py/observer/ObserverAutoComplete.py
py/observer/ObserverConfig.py
py/observer/ObserverTrip.py
qml/observer/BiospecimensScreen.qml
qml/observer/EndTripScreen.qml

More bug fixes after a little bit of field testing:
End Trip Label Update: https://www.fisheries.noaa.gov/jira/browse/FIELD-1372
Sticky permit number: https://www.fisheries.noaa.gov/jira/browse/FIELD-2084
Port substring autocomplete: https://www.fisheries.noaa.gov/jira/browse/FIELD-2086
Biospecimen lengths entry bug: https://www.fisheries.noaa.gov/jira/browse/FIELD-2083

Optecs minor bug clean up after sprint 2

---

py/observer/Biospecimens.py
py/observer/ObserverConfig.py
py/observer/ObserverTrip.py
qml/observer/BiospecimensScreen.qml
qml/observer/ObserverTableView.qml
qml/observer/SpeciesFGScreen.qml
qml/observer/SpeciesScreen.qml

Exclude Sharks, Rays Sturgeon from bs len check: https://www.fisheries.noaa.gov/jira/browse/FIELD-2008
Make Biospecimens tab sortable: https://www.fisheries.noaa.gov/jira/browse/FIELD-2090
Exclude shrimp fisheries from bs len check: https://www.fisheries.noaa.gov/jira/browse/FIELD-1851

Optecs fixes for bug sprint

---

py/observer/Biospecimens.py
py/observer/ObserverConfig.py
py/observer/ObserverTrip.py
qml/observer/BiospecimensScreen.qml
qml/observer/ObserverTableView.qml
qml/observer/SpeciesFGScreen.qml
qml/observer/SpeciesScreen.qml

Adding in final bug fixes, newly merged should be the following:
Shrimp Fishery excluded from low bs len check: https://www.fisheries.noaa.gov/jira/browse/FIELD-1851
Biospecimen table now sortable: https://www.fisheries.noaa.gov/jira/browse/FIELD-2090
Sharks, Rays, Sturgeon excluded from high bs len: https://www.fisheries.noaa.gov/jira/browse/FIELD-2008
Marking this as release v2.1.3+1

Final merge for 2021 season start

---

py/observer/ObserverFishingLocations.py
py/observer/ObserverTabletGPS.py
qml/common/FramButton.qml
qml/observer/GPSEntryDialog.qml

Merged branch contains code to allow users to click a button and populate fishing location information with the timestamp, latitude, and longitude pulled from the GETAC tablets' built in GPS hardware.  See jira ticket: https://www.fisheries.noaa.gov/jira/browse/FIELD-1442

New feature to pull in coordinates from built-in tablet GPS

---

py/observer/ObserverConfig.py
qml/common/FramButton.qml

Bug fix missed reference to parent implicit width attribute in FramButton.qml.

FIELD-2111: FramButton width bug fix

---

py/common/SoundPlayer.py
py/trawl/Settings.py
py/trawl/StateMachine.py
qml/trawl/SettingsScreen.qml

1. Create editable tableview on SettingsScreen
2. Create DEFAULT_SETTINGS table to allow user to revert to default settings when needed
3. Create button and function to reset settings to default
4. Prevent any settings edit if collected data exists in db
5. Allow user to clear out all collected data

#213: Exposing SETTINGS table to UI on SettingsScreen

---

build/build_trawl_analyzer.py
py/hookandline/SensorDataFeeds.py
py/observer/ObserverConfig.py
py/trawl/FishSampling.py
py/trawl/ProtocolViewer.py
py/trawl/SpecialActions.py
qml/trawl/SpecialActionsScreen.qml
qml/trawl/WeighBasketsScreen.qml

See https://github.com/nwfsc-fram/pyFieldSoftware/pull/209 for conversation.  Creating this PR to merge into develop-trawlbackdeck rather than master.
Changes relate to correcting how buttons are created / sliced on SpecialAcionsScreen.qml, and how special projects like Pyrosomes are handled in this screen

Fixes for 2021 special actions (Pyrosomes, coral barcodes, etc)

---

py/observer/ObserverConfig.py
qml/observer/ObserverKeyboardDialog.qml
qml/observer/ObserverLogin.qml

Bumping login keyboard over to left side of screen.
https://www.fisheries.noaa.gov/jira/browse/FIELD-2109

FIELD-2109: login keyboard moved to prevent conflict with other buttons

---

py/observer/ObserverConfig.py
py/observer/ObserverSpecies.py

Skate complex rewritten so that only Skate Unid species will relate to the entire group, whereas others will not be grouped.

FIELD-1900: Ungroup skates except for Skate Unid

---

py/observer/ObserverConfig.py
py/observer/ObserverTabletGPS.py

See https://www.fisheries.noaa.gov/jira/browse/FIELD-2113
Using GPS time (UTC), but adjusting to local time by deriving UTC offset from tablet.

FIELD-2113 Dynamically adjust UTC offset depending on time of year for GPS time

---

main_hookandline_hookmatrix.py
py/hookandline_hookmatrix/HookMatrixConfig.py
py/hookandline_hookmatrix/Settings.py
py/hookandline_hookmatrix/StateMachine.py
qml/hookandline_hookmatrix/HookMatrixStateMachine.qml
qml/hookandline_hookmatrix/SettingsScreen.qml
qml/hookandline_hookmatrix/SitesScreen.qml
qrc/hookandline_hookmatrix.qrc

Users can now update FPC IP address setting via the UI.  Defaults for vessel IP addresses are currently hardcoded into the application for 2021.

#259: Adding settings page to HookMatrix for IP updates
